[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[build-dependencies]
phf_generator = "0.11"
phf = "0.13.1"

[dependencies]
phf = "0.13.1"
fst = "0.4.7"
once_cell = "1.19"
serde_json = "1.0.143"
anyhow = "1.0.99"
hex = "0.4.3"
alloy = { version = "1.0.25", features = ["full"] }